#! /usr/bin/python

## Make sure to set to run at startup in daemon mode

from xbee import ZigBee
import serial, time, sqlite3, os

#PORT = r"\\.\COM10"
PORT = '/dev/ttyUSB0'
BAUD_RATE = 9600
DB = r"/home/pi/StreamMonitorLog.db"

# WAIT for it..
while not os.path.exists(PORT):
    time.sleep(3)

# Open serial port
ser = serial.Serial(PORT, BAUD_RATE)

# Create API object
xbee = ZigBee(ser, escaped=True)

# Connect to DB (also, create DB if it does not exist)
conn = sqlite3.connect(DB)
c = conn.cursor() 

# Find out if table exists
table_exists = False
for table in c.execute("SELECT name FROM sqlite_master WHERE type='table';"):
    if table[0] == 'StreamMonitor':
        table_exists = True

# Create table if it does not exist
if not table_exists:
	c.execute('CREATE TABLE StreamMonitor (turbidity real, temp real, pressure real, battery real)') 

# Infinite loop...
while True:
        response = xbee.wait_read_frame()
        turb = 100. - response['samples'][0]['adc-0']/10.23
        temp = (1.2 * response['samples'][0]['adc-1']/1024.0) / 10.0
        pres = 7.25 * response['samples'][0]['adc-2']/1024.0
        volt = 6.25 * response['samples'][0]['adc-3']/1024.0
        
        c.execute("INSERT INTO StreamMonitor VALUES (%3.1f, %3.1f, %5.2f, %5.2f)" % (turb, temp, pres, volt))
        conn.commit()

conn.close()        
ser.close()

